### ISSUE TITLE
System.DllNotFoundException: libvlc

### ISSUE THREAD

**Issue by mmehdidehghani** [mfkl/libvlc-nuget#17]
I installed LibVLCSharp on my Xamarin.Form project (.Net Standrad 2.0 - Xamarin.Forms v 3.3) accourding to @matt-goldman following steps :

1-  LibVLCSharp and LibVLCSharp.Forms installed in shared project
2-  LibVLCSharp, LibVLCSharp.Forms and VideoLAN.LibVLC.Android installed in Andoid project
3-  updated all packages

But i get the "System.DllNotFoundException: libvlc" error on :
Core.Initialize();
_libVLC = new LibVLC():

**Comment by jeremyVignelles** [comment]
Unless I'm mistaking, you need LibVLCSharp.Forms.Android on your android project.

**Comment by mmehdidehghani** [comment]
Dear jeremyVignelles
Thanks alot for your reply. 🌹🌹🙏🏻🙏🏻 couldn't find LibVLCSharp.Forms.Android NuGet package. Could you please help me how can i do that? 
Best regards.

**Comment by jeremyVignelles** [comment]
I forgot my PC this weekend and was in a middle of the crowd yesterday when I replied.
It seems I was mistaking, there's no such thing as .Forms.Android.
Given I'm on the phone, here is a few things that comes to my mind without the ability to check:

- Did you select a netstandard project or a shared project for your xamarin.forms project? I think we only support the netstandard way.
- Which IDE are you using?
- Which Android SDK are you using?

**Comment by mmehdidehghani** [comment]
Dear @jeremyVignelles 
I'm soooooooooo sorry for my comment in this page: 🙈🙈🙈🙈🙈https://code.videolan.org/videolan/LibVLCSharp/issues/109

Thank you sooooooooooooo much for your reply in your vaction. 🙈🙈🙈🙈🌹🌹🌹🌹

Answer to your questions:
- .Net Standard 2.0
- Visual Studio 2017
- Android 6.0 - API 23

Xamarin.Forms 3.3.0

I hope u will have fun in your vacation
Best Regards

**Comment by jeremyVignelles** [comment]
Can you try targetting android 8.1 or later? seems that LibVLCSharp targets monoandroid81, I don't know if the version are linked...

**Comment by mmehdidehghani** [comment]
Dear @jeremyVignelles 
I attched my settings. 
![capture3](https://user-images.githubusercontent.com/14868539/53298613-ba3d7700-3845-11e9-8b54-37e31dd3d4ae.PNG)

**Comment by jeremyVignelles** [comment]
I've no other idea, can you clone the LibVLCSharp repo and run the Forms.Android project on your device?

**Comment by mmehdidehghani** [comment]
Dear @jeremyVignelles 
Thank you so much for your replies.
I checked it on my device but it didn't work. :(

**Comment by mfkl** [comment]
Share a git repo sp I can reproduce the issue locally.

Next time you spam I ban you.
