### ISSUE TITLE
VideoLAN.LibVLC.Mac for version 4 pre-release channel?

### ISSUE THREAD

**Issue by ghost** [mfkl/libvlc-nuget#30]
Is it possible to get VideoLan.LibVLC.Mac nuget for the version 4 pre release channel for testing purposes?

Is it possible to make it available, since it seems that VideoLan.LibVLC.Mac version 3.1.3.1 does not work with version 4 pre-release of LibVLCSharp and LibVLCSharp.Forms?

**Comment by mfkl** [comment]
Yes, but [this](https://github.com/videolan/libvlcsharp/pull/163) needs to be fixed first before we can do proper continuous delivery for libvlc 4 for macOS. Help welcome :-)

**Comment by mfkl** [comment]
Also see https://github.com/mfkl/libvlc-nuget/issues/11
