### ISSUE TITLE
How to fully exclude x86?

### ISSUE THREAD

**Issue by Mgamerz** [mfkl/libvlc-nuget#31]
I'm have an x64-only application that makes use of this lib. Using your includes feature we have trimmed the size of the x64 native libs down to a reasonable size. However, in deployment there is also the full library of x86 files that is being included, which has no value to my app (it's over 150MB). I looked over your documentation (https://github.com/mfkl/libvlc-nuget/blob/master/cherry-picking.md) and I can't figure out how to just exclude everything from win-x86.

Is there a trick to fully excluding x86 libraries?

**Comment by mfkl** [comment]
Can you share your csproj and deployment/build commands please?

This should do it
```
<VlcWindowsX64ExcludeFiles Include="libvlc.%2A;libvlccore.%2A;hrtfs\%2A%2A;locale\%2A%2A;lua\%2A%2A;plugins\%2A%2A" />
```

**Comment by jeremyVignelles** [comment]
You didn't look at the correct doc.
Please look at this :
https://www.github.com/mfkl/libvlc-nuget/tree/master/library-copy-enabling.md

Either change your build platform to x64 instead of AnyCPU for the autodetection to work, or just set `<VlcWindowsX86Enabled>false</<VlcWindowsX86Enabled>`

**Comment by mfkl** [comment]
Closing as answered
