### ISSUE TITLE
Can you fix the bug that gets stuck when playing some videos?

### ISSUE THREAD

**Issue by bbhxwl** [mfkl/libvlc-nuget#33]
Can you fix the bug that gets stuck when playing some videos?

https://bj.bcebos.com/kpy-organizations/U12760068/videos/2021083110332897820349837654.mp4

**Comment by jeremyVignelles** [comment]
Please get an interpret, follow the rules and our instructions, post on the proper repo and stop spamming everywhere or you'll get banned from everywhere.

**Comment by bbhxwl** [comment]
> Please get an interpret, follow the rules and our instructions, post on the proper repo and stop spamming everywhere or you'll get banned from everywhere.

https://code.videolan.org/videolan/LibVLCSharp/-/issues/500

I didn't send spam. Pure manual typing. There are bugs. I think I've sent the details. Can't you understand the text translated by Google?
