### ISSUE TITLE
Support decode flv with hevc(h265) codec

### ISSUE THREAD

**Issue by shushu789** [mfkl/libvlc-nuget#41]
Hello, is it possible to build a library that supports decoding flv with hevc (h265) codec, I know this project is consistent with the official one, since the official one does not support flv with hevc (h265) codec by default, so I would like to Learn how to solve this problem. I don't know C language, but I need to use libvlc in C#. This problem is similar to the fact that ffmpeg does not officially support rtmp hevc (h265) encoding. Refer to the link:(https://trac.ffmpeg.org/ticket/6389). But the problem of ffmpeg has been supported in many places, such as this: (https://github.com/yt-dlp/FFmpeg-Builds#2-support-for-hevc-over-flv), it is yt-dlp constructed. Thanks in advance, sorry for the inconvenience

**Comment by jeremyVignelles** [comment]
Please use [this bugtracker](https://code.videolan.org/videolan/vlc) to request VLC features. This repository is just repackaging the VLC libraries to make use of them in your .net app.

**Comment by mfkl** [comment]
We are working to update the FLV specs to include support for h265. In the meantime,  you can contact [videolabs](https://videolabs.io/) for more information and commercial services about this issue.
