### ISSUE TITLE
Cherry picking clarification and help please

### ISSUE THREAD

**Issue by RobG66** [mfkl/libvlc-nuget#46]
I read the following:
https://github.com/mfkl/libvlc-nuget/blob/master/cherry-picking.md

 But I am just not sure how to proceed.  

 I followed an example from here:
https://stackoverflow.com/questions/66369575/wpf-libvlcsharp-integration-in-setup-project-release-version

 But this breaks things.  I have a 1mb application and would like to reduce the whole package by as much as possible.  All I need is simple video playback, including mpeg4 codec.  

 Using VS2022 (Windows) and I wrote a C# winforms application.  With the full libvlcsharp package from nuget I have no issue getting videos to play.  It's just the size of my package is way too big now. I just don't know how to proceed from here.  I excluded x86 which obviously helps, but not enough.

 Any help is appreciated.

Rob

**Comment by mfkl** [comment]
Hi Rob,

Due to lack of resources, community support is best effort. All the code and docs and examples are publicly available.

If you need more help, I'd direct you to commercial support through https://videolabs.io/store.

Thanks.
