### ISSUE TITLE
Can this be consumed from C#?

### ISSUE THREAD

**Issue by JunielKatarn** [mfkl/libvlc-nuget#6]
I'm not familiar with the terms used in the README.

Is this a .NET-capable library?
Does it provide a set of MSIL types?

**Comment by mfkl** [comment]
> I'm not familiar with the terms used in the README.

Which terms? So I can clarify for others.

> Is this a .NET-capable library?
 >Does it provide a set of MSIL types?

This is NOT a .NET capable library, this is a native C/C++ library. It does not provide a set of MSIL types.
However, it can be consumed by .NET by using a "wrapper" library, which is a .NET library offering MSIL types in a friendly .NET API and handling the marshaling job between native and managed code.
I'm working on a Xamarin one that I plan to release on nuget very soon: https://github.com/mfkl/LibVLCSharp
If you plan to target Windows only:
For WPF/WinForms I recommend https://github.com/ZeBobo5/Vlc.DotNet/ made by community and pretty mature.
For UWP: https://github.com/kakone/libVLCX (C++/CX) which is what https://github.com/kakone/VLC.MediaElement and https://github.com/videolan/vlc-winrt use.

**Comment by mfkl** [comment]
Updated the readme with nuget info https://github.com/mfkl/LibVLCSharp

**Comment by JunielKatarn** [comment]
Understood. Looking forward to LibVLCSharp!
